### PR TITLE
TypeError: 'type' object is not subscriptable

### PR DESCRIPTION
**Pull request by GreemDark**

### CODE REVIEW

**Comment by primal100** [comment]
Thanks @GreemDark.

I was wondering why I didn't encounter this error and it's because it only occurs in Python <= 3.8.

One question, why did you change str to AnyStr (str+bytes). A bytes object will fail when passed to re.match.

**Comment by GreemDark** [comment]
I used parts of code from other libraries
here for example: 
https://github.com/davidhalter/typeshed/blob/ae9d4f4b21bb5e1239816c301da7b1ea904b44c3/stdlib/3/typing.pyi#L571

**Review by primal100 — APPROVED** [review]
Looks good, will allow str and bytes and typing and will make another pull request to support bytes

**Comment by primal100** [comment]
Latest version 2.0.5 with this fix now on pypi. Please upgrade. Thank you for your contribution.

**Pull request merged**
